openapi: 3.0.0
info:
  title: Folksoul API
  description: Documentation for folksoul API
  version: 1.0.0

servers:
  - url: http://localhost:3000/
    description: local server
paths:
  /login:
    post:
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nickname:
                  type: string
                password:
                  type: string
              example:
                nickname: user
                password: folksoul
              required:
                - nickname
                - password
      responses:
        '200':
          description: Successfully logged in
        '400':
          description: Wrong nickname or password
        '422':
          description: Invalid request body formation
